/** Chaves e URLs dos mapas Tiled (.tmx). */
export const MAP_KEYS = {
  leafVillage: 'leafVillage',
  /** Hub ilustrado Konoha (PNG + colisão TMX). */
  leafVillageHub: 'leafVillageHub',
  /** Hub lateral interdimensional (PNG + colisão TMX). */
  hubInterdimensional: 'hubInterdimensional',
  forest: 'forest',
  /** Arena visual de clareira (fallback / legado). */
  huntForestClearing: 'huntForestClearing',
  huntArenaExameChunnin: 'huntArenaExameChunnin',
  /** Arena Exame Chunin (lateral 4K — MAPAS 3). */
  huntArenaExameChunin: 'huntArenaExameChunin',
  huntCampoTreinamento: 'huntCampoTreinamento',
  huntEsconderijoAkatsuki: 'huntEsconderijoAkatsuki',
  huntKonohaDestruida: 'huntKonohaDestruida',
  huntLabOrochimaru: 'huntLabOrochimaru',
  huntPaisDoVento: 'huntPaisDoVento',
  huntPontePaisOnda: 'huntPontePaisOnda',
  huntValeDoFim: 'huntValeDoFim',
  /** Teste: combate lateral 1v1 (Itachi → Rock Lee). */
  huntValeDoFimLateral: 'huntValeDoFimLateral',
  /** Teste: Vale do Fim em vídeo loop. */
  huntValeLoop: 'huntValeLoop',
  huntMonteMyoboku: 'huntMonteMyoboku',
  huntDistritoUchiha: 'huntDistritoUchiha',
  huntCampoGuerraNinja: 'huntCampoGuerraNinja',
  /** Arredores do Reino Clover (arena lateral Black Clover). */
  huntArredoresReinoClover: 'huntArredoresReinoClover',
  huntNamekusei: 'huntNamekusei',
  huntJogosCell: 'huntJogosCell',
  huntTorneioArtesMarciais: 'huntTorneioArtesMarciais',
  huntSalaDoTempo: 'huntSalaDoTempo',
  /** Deserto rochoso Saiyajin (lateral 4K). */
  huntDesertoSaiyajin: 'huntDesertoSaiyajin',
  /** Teste: caça top-down 3072² com equipe de 3 e câmera seguindo o líder. */
  huntTesteEquipe: 'huntTesteEquipe',
  /** Teste: floresta upscale 5016² (crop 5008) com equipe e câmera no líder. */
  huntTesteFarmWonsr: 'huntTesteFarmWonsr',
  /** Teste: floresta aberta (mesmo mundo do mapa teste) com Tiny RPG Demon_A. */
  huntTesteDemon: 'huntTesteDemon',
  /** Teste: floresta aberta com outfits de monstros WONSR (lookType). */
  huntTesteWonsrMonsters: 'huntTesteWonsrMonsters',
  /** Recorte top-down WONSR: farm Anbu (96×96 tiles). */
  wonsrFarmAnbu: 'wonsrFarmAnbu',
  academy: 'academy',
  wonsrKonoha: 'wonsrKonoha',
  /** Top-down 3840×2160 — mapas WONSR legado + aba NARUTO TOP DOWN (arenas amplas). */
  huntWonsrFlorestaDaMorte: 'huntWonsrFlorestaDaMorte',
  huntWonsrCampoTreinamento: 'huntWonsrCampoTreinamento',
  huntWonsrCavernaAkatsuki: 'huntWonsrCavernaAkatsuki',
  huntWonsrDesertoAreia: 'huntWonsrDesertoAreia',
  huntWonsrEsconderijoOrochimaru: 'huntWonsrEsconderijoOrochimaru',
  huntWonsrPaisDoFerro: 'huntWonsrPaisDoFerro',
  huntWonsrPonteDaNevoa: 'huntWonsrPonteDaNevoa',
  huntWonsrValeDasEstatuas: 'huntWonsrValeDasEstatuas',
  huntWonsrClareiraEquipe7: 'huntWonsrClareiraEquipe7',
  huntWonsrLaboratorioOrochimaru: 'huntWonsrLaboratorioOrochimaru',
  huntTdValeDoFim: 'huntTdValeDoFim',
  huntTdArenaExameChunin: 'huntTdArenaExameChunin',
  huntTdPonteDasOndas: 'huntTdPonteDasOndas',
  huntTdClareiraEquipe7: 'huntTdClareiraEquipe7',
  huntTdCavernaAkatsuki: 'huntTdCavernaAkatsuki',
  huntTdCrateraKonoha: 'huntTdCrateraKonoha',
  huntTdLaboratorioOrochimaru: 'huntTdLaboratorioOrochimaru',
  huntTdArenaVilaAreia: 'huntTdArenaVilaAreia',
  /** MAPAS NOVOS — 5 artes extras (13 top-down no total). */
  huntTdIlhaTartaruga: 'huntTdIlhaTartaruga',
  huntTdMonteMyoboku: 'huntTdMonteMyoboku',
  huntTdUzushiogakure: 'huntTdUzushiogakure',
  huntTdCampoUchiha: 'huntTdCampoUchiha',
  huntTdHospitalKonoha: 'huntTdHospitalKonoha',
} as const;

export type MapKey = (typeof MAP_KEYS)[keyof typeof MAP_KEYS];

export const MAP_FILES: Record<MapKey, string> = {
  leafVillage: '/maps/leafVillage.tmx',
  leafVillageHub: '/maps/leaf-village-hub.tmx',
  hubInterdimensional: '/maps/hub-interdimensional.tmx',
  // Área de caça = recorte de floresta do WONSR (render PNG + colisão do TMX).
  forest: '/maps/wonsr-forest.tmx',
  huntForestClearing: '/maps/hunt-forest-clearing.tmx',
  huntArenaExameChunnin: '/maps/hunt-arena-exame-chunnin.tmx',
  huntArenaExameChunin: '/maps/hunt-arena-exame-chunin.tmx',
  huntCampoTreinamento: '/maps/hunt-campo-treinamento.tmx',
  huntEsconderijoAkatsuki: '/maps/hunt-esconderijo-akatsuki.tmx',
  huntKonohaDestruida: '/maps/hunt-konoha-destruida.tmx',
  huntLabOrochimaru: '/maps/hunt-lab-orochimaru.tmx',
  huntPaisDoVento: '/maps/hunt-pais-do-vento.tmx',
  huntPontePaisOnda: '/maps/hunt-ponte-pais-onda.tmx',
  huntValeDoFim: '/maps/hunt-vale-do-fim.tmx',
  huntValeDoFimLateral: '/maps/hunt-vale-do-fim-lateral.tmx',
  huntValeLoop: '/maps/hunt-vale-loop.tmx',
  huntMonteMyoboku: '/maps/hunt-monte-myoboku.tmx',
  huntDistritoUchiha: '/maps/hunt-distrito-uchiha.tmx',
  huntCampoGuerraNinja: '/maps/hunt-campo-guerra-ninja.tmx',
  huntArredoresReinoClover: '/maps/hunt-arredores-reino-clover.tmx',
  huntNamekusei: '/maps/hunt-namekusei.tmx',
  huntJogosCell: '/maps/hunt-jogos-cell.tmx',
  huntTorneioArtesMarciais: '/maps/hunt-torneio-artes-marciais.tmx',
  huntSalaDoTempo: '/maps/hunt-sala-do-tempo.tmx',
  huntDesertoSaiyajin: '/maps/hunt-deserto-saiyajin.tmx',
  // Reaproveita o recorte top-down de Konoha (PNG + colisão) como mapa de teste.
  huntTesteEquipe: '/maps/wonsr-konoha.tmx',
  // Colisão derivada da própria arte (scripts/install-teste-clareira-map.js).
  huntTesteFarmWonsr: '/maps/hunt-teste-clareira.tmx',
  huntTesteDemon: '/maps/hunt-teste-clareira.tmx',
  huntTesteWonsrMonsters: '/maps/hunt-teste-clareira.tmx',
  academy: '/maps/academy.tmx',
  wonsrKonoha: '/maps/wonsr-konoha.tmx',
  wonsrFarmAnbu: '/maps/wonsr-farm-anbu.tmx',
  huntWonsrFlorestaDaMorte: '/maps/wonsr-floresta-da-morte.tmx?v=tdnov2026',
  huntWonsrCampoTreinamento: '/maps/wonsr-campo-treinamento.tmx?v=tdnov2026',
  huntWonsrCavernaAkatsuki: '/maps/wonsr-caverna-akatsuki.tmx?v=tdnov2026',
  huntWonsrDesertoAreia: '/maps/wonsr-deserto-areia.tmx?v=tdnov2026',
  huntWonsrEsconderijoOrochimaru: '/maps/wonsr-esconderijo-orochimaru.tmx?v=tdnov2026',
  huntWonsrPaisDoFerro: '/maps/wonsr-pais-do-ferro.tmx?v=tdnov2026',
  huntWonsrPonteDaNevoa: '/maps/wonsr-ponte-da-nevoa.tmx?v=tdnov2026',
  huntWonsrValeDasEstatuas: '/maps/wonsr-vale-das-estatuas.tmx?v=tdnov2026',
  huntWonsrClareiraEquipe7: '/maps/wonsr-clareira-equipe-7.tmx?v=tdnov2026',
  huntWonsrLaboratorioOrochimaru: '/maps/wonsr-laboratorio-orochimaru.tmx?v=tdnov2026',
  huntTdValeDoFim: '/maps/hunt-td-vale-do-fim.tmx?v=tdnov2026',
  huntTdArenaExameChunin: '/maps/hunt-td-arena-exame-chunin.tmx?v=tdnov2026',
  huntTdPonteDasOndas: '/maps/hunt-td-ponte-das-ondas.tmx?v=tdnov2026',
  huntTdClareiraEquipe7: '/maps/hunt-td-clareira-equipe-7.tmx?v=tdnov2026',
  huntTdCavernaAkatsuki: '/maps/hunt-td-caverna-akatsuki.tmx?v=tdnov2026',
  huntTdCrateraKonoha: '/maps/hunt-td-cratera-konoha.tmx?v=tdnov2026',
  huntTdLaboratorioOrochimaru: '/maps/hunt-td-laboratorio-orochimaru.tmx?v=tdnov2026',
  huntTdArenaVilaAreia: '/maps/hunt-td-arena-vila-areia.tmx?v=tdnov2026',
  huntTdIlhaTartaruga: '/maps/hunt-td-ilha-tartaruga.tmx?v=tdnov2026',
  huntTdMonteMyoboku: '/maps/hunt-td-monte-myoboku.tmx?v=tdnov2026',
  huntTdUzushiogakure: '/maps/hunt-td-uzushiogakure.tmx?v=tdnov2026',
  huntTdCampoUchiha: '/maps/hunt-td-campo-uchiha.tmx?v=tdnov2026',
  huntTdHospitalKonoha: '/maps/hunt-td-hospital-konoha.tmx?v=tdnov2026',
};
